# Generated by Django 4.2 on 2024-10-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('template_body', models.TextField()),
                ('template_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='static/')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the tenant is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tenants',
                'db_table': 'wa_tenant',
            },
        ),
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('request_name', models.CharField(max_length=100)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database.notificationtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database.tenant')),
            ],
            options={
                'verbose_name_plural': 'Notification Requests',
                'db_table': 'notification_request',
            },
        ),
    ]
