# Generated by Django 4.2 on 2025-02-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_tenant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the recipient is currently active.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='database.tenant')),
            ],
            options={
                'verbose_name_plural': 'Recipients',
                'db_table': 'recipient',
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
