# Generated by Django 4.2 on 2025-02-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantStorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('azure', 'Azure'), ('aws', 'AWS'), ('gcp', 'GCP')], max_length=100)),
                ('account_name', models.CharField(help_text='Storage Account Name', max_length=255)),
                ('account_key', models.CharField(blank=True, help_text='Storage Account Key or equivalent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='storage_settings', to='database.tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenant Storage Settings',
                'db_table': 'tenant_storage_settings',
            },
        ),
    ]
